### ISSUE TITLE
Bug: build-nodejs20.x requires LD_LIBRARY_PATH= to run SAM CLI commands

### ISSUE THREAD

**Issue by gws** [aws/aws-sam-build-images#115]
### Description:

The `build-nodejs20.x` variant of the image breaks when running `sam` commands such as `sam validate` unless the environment variable `LD_LIBRARY_PATH` is set and empty.

This is mentioned here: https://github.com/aws/aws-sam-build-images/blob/1ef755719b5a1b1ed02ab156f31b90acef268c96/tests/build_image_base_test.py#L92

Is it expected that users of the `nodejs20.x` image will need to set `LD_LIBRARY_PATH=` in order to run `sam` commands, and if so is this documented somewhere? Is this a temporary situation?

### Steps to reproduce:
1. Run the following command:
   ```
   docker run -it --rm -w /work -v $(pwd):/work public.ecr.aws/sam/build-nodejs20.x:1.103 sam validate --lint
   ```

### Observed result:

```
2023-11-18 05:55:33 Command 'validate' is not configured correctly. Unable to import 'samcli.commands.validate.validate'
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/cli/command.py", line 263, in get_command
    mod = importlib.import_module(pkg_name)
  File "/usr/lib64/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/samcli/commands/validate/validate.py", line 6, in <module>
    import boto3
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/boto3/__init__.py", line 17, in <module>
    from boto3.session import Session
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/boto3/session.py", line 17, in <module>
    import botocore.session
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/session.py", line 26, in <module>
    import botocore.client
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/client.py", line 15, in <module>
    from botocore import waiter, xform_name
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/waiter.py", line 18, in <module>
    from botocore.docs.docstring import WaiterDocstring
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/docs/__init__.py", line 15, in <module>
    from botocore.docs.service import ServiceDocumenter
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/docs/service.py", line 14, in <module>
    from botocore.docs.client import (
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/docs/client.py", line 18, in <module>
    from botocore.docs.example import ResponseExampleDocumenter
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/docs/example.py", line 13, in <module>
    from botocore.docs.shape import ShapeDocumenter
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/docs/shape.py", line 19, in <module>
    from botocore.utils import is_json_value_header
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/utils.py", line 38, in <module>
    import botocore.httpsession
  File "/usr/local/opt/sam-cli/lib64/python3.9/site-packages/botocore/httpsession.py", line 22, in <module>
    from urllib3.util.ssl_ import (
ImportError: cannot import name 'ssl' from 'urllib3.util.ssl_' (/usr/local/opt/sam-cli/lib64/python3.9/site-packages/urllib3/util/ssl_.py)
Usage: sam [OPTIONS] COMMAND [ARGS]...
Try 'sam -h' for help.

Error: No such command 'validate'.
```

### Expected result:

Running the following command:

`docker run -it --rm -e 'LD_LIBRARY_PATH=' -w /work -v $(pwd):/work public.ecr.aws/sam/build-nodejs20.x:1.103 sam validate --lint`

instead produces the following expected output (modulo the `RuntimeWarning`):

```
        SAM CLI now collects telemetry to better understand customer needs.

        You can OPT OUT and disable telemetry collection by setting the
        environment variable SAM_CLI_TELEMETRY=0 in your shell.
        Thanks for your help!

        Learn More: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-telemetry.html

/usr/local/opt/sam-cli/lib64/python3.9/site-packages/networkx/utils/backends.py:135: RuntimeWarning: networkx backend defined more than once: nx-loopback
  backends.update(_get_backends("networkx.backends"))
/work/template.yaml is a valid SAM Template
```

**Comment by hnnasit** [comment]
Hi @gws, thanks for reporting this issue. The team is already aware about this and I have opened an [issue](https://github.com/aws/aws-sam-build-images/issues/116) with more information about this. I am closing this issue in favor of the issue I created. Please track that issue for any updates.
