### ISSUE TITLE
Permission problems when doing builds in a CI environment

### ISSUE THREAD

**Issue by twasink** [aws/aws-sam-build-images#41]
I'm getting permission errors using the sam build images on my Jenkins server (which itself is run as an ECS task, so it's docker-in-docker, if that makes a difference).

The build executes fine - but after the build process, it gets this error:

```
+ sam build
Building codeuri: /var/jenkins_home/workspace/.../hello_world runtime: python3.8 metadata: {} architecture: x86_64 functions: ['HelloWorldFunction']
Running PythonPipBuilder:ResolveDependencies
Running PythonPipBuilder:CopySource

Build Succeeded

Built Artifacts  : .aws-sam/build
Built Template   : .aws-sam/build/template.yaml

Commands you can use next
=========================
[*] Invoke Function: sam local invoke
[*] Test Function in the Cloud: sam sync --stack-name {stack-name} --watch
[*] Deploy: sam deploy --guided
        
Traceback (most recent call last):
  File "/usr/local/opt/sam-cli/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 142, in wrapped
    metric = Metric(metric_name)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 309, in __init__
    self._add_common_metric_attributes()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 332, in _add_common_metric_attributes
    self._data["installationId"] = self._gc.installation_id
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 351, in installation_id
    self.set_value(DefaultEntry.INSTALLATION_ID, value)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 273, in set_value
    self._set_value(config_entry, value, is_flag, flush)
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 294, in _set_value
    self._write_config()
  File "/usr/local/opt/sam-cli/lib/python3.8/site-packages/samcli/cli/global_config.py", line 324, in _write_config
    self.config_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
  File "/var/lang/lib/python3.8/pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/.aws-sam'
script returned exit code 1
```

This doesn't happen when running locally. It looks a lot like it's trying to go to `${HOME}/.aws-sam` - and the Jenkins server, running as it is as a daemon, doesn't have a home directory.

This happens with (at least) the current nodejs12.x, nodejs14.x, python3.8 and python 3.9 images. It does _not_ happen with the older images still up on Docker Hub (tested nodejs12.x and python3.8).

**Comment by twasink** [comment]
I'm going to run some experiments to see if it happens with the older versions on the AWS Registry, and then to see if I can see where it crept in.

**Comment by twasink** [comment]
Okay, I can confirm that it works with 1.32 (which matches the version on Docker Hub), and 1.33. It does _not_ work with 1.34, so that's presumably where the regression crept i.
