### ISSUE TITLE
Access denied for image pull using latest SAM

### ISSUE THREAD

**Issue by wcom939** [aws/aws-sam-build-images#42]
Invoking com.somecompany.aws.handler.GatewayHandler (java8)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-java8
Building image......
Failed to build Docker Image
NoneType: None
Error: Error building docker image: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

This is using latest intellij with latest aws toolbox, with latest sam

**Comment by hoffa** [comment]
Do you still have this issue?

I'm not able to reproduce:

```
% docker pull public.ecr.aws/sam/emulation-java8
Using default tag: latest
latest: Pulling from sam/emulation-java8
b844c5fb5a5a: Pull complete 
e4167c993ac8: Pull complete 
e3b91baeb2b6: Pull complete 
Digest: sha256:7b50d8df0b2f99c3ceac8c9ebb8849c6f4be419c5301d03b19e61f052f97edd5
Status: Downloaded newer image for public.ecr.aws/sam/emulation-java8:latest
public.ecr.aws/sam/emulation-java8:latest
```

**Comment by c2tarun** [comment]
There has been no activity for around 6 days and we are not able to reproduce the issue. I am resolving this issue for now, please re-open if you have any questions.

**Comment by sambler** [comment]
I started getting this error yesterday starting a python env.  I notice that there are two variations of the error message.

`Client.Timeout exceeded while awaiting headers`

and 

`context deadline exceeded`

I get similar errors manually calling docker pull

```
% docker pull public.ecr.aws/sam/emulation-python3.8
Using default tag: latest
Error response from daemon: Get "https://public.ecr.aws/v2/": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
% docker pull public.ecr.aws/sam/emulation-python3.8
Using default tag: latest
Error response from daemon: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

```
2022-02-14 19:39:18  * Running on http://192.168.8.104:3000/ (Press CTRL+C to quit)
Invoking app.lambda_handler (python3.8)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image......
Failed to build Docker Image
NoneType: None
Exception on /hello [GET]
Traceback (most recent call last):
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shane/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 356, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 230, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 178, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 93, in __init__
    image = LambdaContainer._get_image(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 236, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture, function_name=function_name)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 163, in build
    self._build_image(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 278, in _build_image
    raise ImageBuildException("Error building docker image: {}".format(log["error"]))
samcli.commands.local.cli_common.user_exceptions.ImageBuildException: Error building docker image: Get "https://public.ecr.aws/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2022-02-14 19:39:40 192.168.8.155 - - [14/Feb/2022 19:39:40] "GET /hello HTTP/1.1" 502 -

Invoking app.lambda_handler (python3.8)
Image was not found.
Removing rapid images for repo public.ecr.aws/sam/emulation-python3.8
Building image......
Failed to build Docker Image
NoneType: None
Exception on /hello [GET]
Traceback (most recent call last):
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/shane/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/shane/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/apigw/local_apigw_service.py", line 356, in _request_handler
    self.lambda_runner.invoke(route.function_name, event, stdout=stdout_stream_writer, stderr=self.stderr)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/commands/local/lib/local_lambda.py", line 137, in invoke
    self.local_runtime.invoke(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/lib/telemetry/metric.py", line 230, in wrapped_func
    return_value = func(*args, **kwargs)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 178, in invoke
    container = self.create(function_config, debug_context, container_host, container_host_interface)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/lambdafn/runtime.py", line 73, in create
    container = LambdaContainer(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 93, in __init__
    image = LambdaContainer._get_image(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_container.py", line 236, in _get_image
    return lambda_image.build(runtime, packagetype, image, layers, architecture, function_name=function_name)
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 163, in build
    self._build_image(
  File "/home/shane/.local/lib/python3.8/site-packages/samcli/local/docker/lambda_image.py", line 278, in _build_image
    raise ImageBuildException("Error building docker image: {}".format(log["error"]))
samcli.commands.local.cli_common.user_exceptions.ImageBuildException: Error building docker image: Get "https://public.ecr.aws/v2/": context deadline exceeded
2022-02-14 19:42:46 192.168.8.155 - - [14/Feb/2022 19:42:46] "GET /hello HTTP/1.1" 502 -
```
